version: "3.7"
services:
  blynk:
    build: .
    container_name: ${PROJECT_NAME}_server
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.blynk.entrypoints=http"
      - "traefik.http.routers.blynk.rule=Host(`${BLYNK_HOST}`)"
      - "traefik.http.services.blynk.loadbalancer.server.port=${BLYNK_HTTP_PORT}"
      - "traefik.http.routers.blynk-sec.entrypoints=https"
      - "traefik.http.routers.blynk-sec.rule=Host(`${BLYNK_HOST}`)"
      - "traefik.http.services.blynk-sec.loadbalancer.server.port=${BLYNK_HTTPS_PORT}"
      - "traefik.http.routers.blynk-sec.tls=true"
      - "traefik.http.routers.blynk-sec.tls.options=myTLSOptions@file"
      - "traefik.http.routers.blynk-sec.tls.certresolver=le"
      - "traefik.http.routers.blynk-sec.service=api@internal"
    restart: always
    ports:
      - ${BLYNK_HTTP_PORT}
      - ${BLYNK_HTTPS_PORT}
    environment:
      BLYNK_HOST: ${BLYNK_HOST}
      BLYNK_FOLDER: ${BLYNK_FOLDER}
      BLYNK_DATA_FOLDER: ${BLYNK_DATA_FOLDER}
      BLYNK_CONFIG_FOLDER: ${BLYNK_CONFIG_FOLDER}
      BLYNK_LOG_FOLDER: ${BLYNK_LOG_FOLDER}
      BLYNK_ADMIN_EMAIL: ${BLYNK_ADMIN_EMAIL}
      BLYNK_ADMIN_PASSWORD: ${BLYNK_ADMIN_PASSWORD}
      BLYNK_CONTACT_EMAIL: ${BLYNK_CONTACT_EMAIL}
      BLYNK_HTTP_PORT: ${BLYNK_HTTP_PORT}
      BLYNK_HTTPS_PORT: ${BLYNK_HTTPS_PORT}
      BLYNK_DOWNLOAD_URL: ${BLYNK_DOWNLOAD_URL}
    networks:
      - web

networks:
  web:
    external: true