version: "3.7"
services:
  blynk:
    build: .
    container_name: ${PROJECT_NAME}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${BLYNK_CONFIG_HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME}.service=${PROJECT_NAME}"
      - "traefik.http.routers.${PROJECT_NAME}.port=${BLYNK_CONFIG_HTTP_PORT}"
      - "traefik.http.services.${PROJECT_NAME}.loadbalancer.servers.port=${BLYNK_CONFIG_HTTP_PORT}"
      - "traefik.http.routers.${PROJECT_NAME}-sec.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}-sec.rule=Host(`${BLYNK_CONFIG_HOST}`)"
      - "traefik.http.routers.${PROJECT_NAME}-sec.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}-sec.service=${PROJECT_NAME}-sec"
      - "traefik.http.routers.${PROJECT_NAME}-sec.port=${BLYNK_CONFIG_HTTPS_PORT}"
      - "traefik.http.services.${PROJECT_NAME}-sec.loadbalancer.servers.port=${BLYNK_CONFIG_HTTPS_PORT}"
    restart: always
    expose:
      - ${BLYNK_CONFIG_HTTP_PORT}
      - ${BLYNK_CONFIG_HTTPS_PORT}
    ports:
      - ${BLYNK_CONFIG_HTTP_PORT}:${BLYNK_CONFIG_HTTP_PORT}
      - ${BLYNK_CONFIG_HTTPS_PORT}:${BLYNK_CONFIG_HTTPS_PORT}
    environment:
      BLYNK_HOST: ${BLYNK_CONFIG_HOST}
      BLYNK_FOLDER: /blynk
      BLYNK_DATA_FOLDER: /blynk/data
      BLYNK_CONFIG_FOLDER: /blynk/config
      BLYNK_LOG_FOLDER: /blynk/log
      BLYNK_ADMIN_EMAIL: ${BLYNK_CONFIG_ADMIN_EMAIL}
      BLYNK_ADMIN_PASSWORD: ${BLYNK_CONFIG_ADMIN_PASSWORD}
      BLYNK_CONTACT_EMAIL: ${BLYNK_CONFIG_CONTACT_EMAIL}
      BLYNK_HTTP_PORT: ${BLYNK_CONFIG_HTTP_PORT}
      BLYNK_HTTPS_PORT: ${BLYNK_CONFIG_HTTPS_PORT}
      BLYNK_LOG_LEVEL: ${BLYNK_CONFIG_LOG_LEVEL}
      BLYNK_USER_DASHBOARD_MAX_LIMIT: ${BLYNK_CONFIG_USER_DASHBOARD_MAX_LIMIT}
      BLYNK_USER_MESSAGE_QUOTA_LIMIT: ${BLYNK_CONFIG__USER_MESSAGE_QUOTA_LIMIT}
      BLYNK_NOTIFICATIONS_FREQUENCY_USER_QUOTA_LIMIT: ${BLYNK_CONFIG_NOTIFICATIONS_FREQUENCY_USER_QUOTA_LIMIT}
      BLYNK_USER_PROFILE_MAX_SIZE: ${BLYNK_CONFIG_USER_PROFILE_MAX_SIZE}
      BLYNK_TERMINAL_STRINGS_POOL_SIZE: ${BLYNK_CONFIG_TERMINAL_STRINGS_POOL_SIZE}
      BLYNK_NOTIFICATIONS_QUEUE_LIMIT: ${BLYNK_CONFIG_NOTIFICATIONS_QUEUE_LIMIT}
      BLYNK_BLOCKING_PROCESSOR_THREAD_POOL_LIMIT: ${BLYNK_CONFIG_BLOCKING_PROCESSOR_THREAD_POOL_LIMIT}
      BLYNK_PROFILE_SAVE_WORKER_PERIOD: ${BLYNK_CONFIG_PROFILE_SAVE_WORKER_PERIOD}
      BLYNK_HARD_SOCKET_IDLE_TIMEOUT: ${BLYNK_CONFIG_HARD_SOCKET_IDLE_TIMEOUT}
      BLYNK_ENABLE_RAW_DATA_STORE: ${BLYNK_CONFIG_ENABLE_RAW_DATA_STORE}
      BLYNK_ADMIN_ROOT_PATH: ${BLYNK_CONFIG_ADMIN_ROOT_PATH}
      BLYNK_ALLOWED_ADMIN_IPS: ${BLYNK_CONFIG_ALLOWED_ADMIN_IPS}
      BLYNK_SSL_CERT: ${BLYNK_CONFIG_SSL_CERT}
      BLYNK_SSL_KEY: ${BLYNK_CONFIG_SSL_KEY}
      BLYNK_SSL_KEY_PASS: ${BLYNK_CONFIG_SSL_KEY_PASS}
      BLYNK_DOWNLOAD_URL: ${BLYNK_DOWNLOAD_URL}
      BLYNK_SMTP_USERNAME: ${BLYNK_SMTP_USERNAME}
      BLYNK_SMTP_PORT: ${BLYNK_SMTP_PORT}
      BLYNK_SMTP_PASSWORD: ${BLYNK_SMTP_PASSWORD}
      BLYNK_SMTP_AUTH: ${BLYNK_SMTP_AUTH}
      BLYNK_SMTP_STARTTLS: ${BLYNK_SMTP_STARTTLS}
      BLYNK_SMTP_TIMEOUT: ${BLYNK_SMTP_TIMEOUT}
      BLYNK_SMTP_HOST: ${BLYNK_SMTP_HOST}
      BLYNK_SMTP_CONNECTIONTIMEOUT: ${BLYNK_SMTP_CONNECTIONTIMEOUT}
    volumes:
      - ./data/:/blynk/data/
      - ./log/:/blynk/log/
      - ./config/:/blynk/config/
    networks:
      - web

networks:
  web:
    external: true